SET search_path TO security;

INSERT INTO users (
  id,
  first_name,
  last_name,
  full_name,
  social_name,
  username,
  email,
  email_verified,
  password,
  password_last_updated,
  account_locked,
  origin,
  interface_theme,
  timezone,
  notifications_enabled,
  login_attempts,
  first_login,
  preferred_language,
  cpf,
  birth_date,
  status_id,
  created_at,
  updated_at
) VALUES (
  '54b445e2-2d95-471b-9dec-a6a2c1f9808e',
  'Usuario',
  'Comum',
  'Usuario Comum',
  NULL,
  'usuariocomum',
  'usuario@empresa.com',
  true,
  '$2a$10$Gj98gcfDW5o1hRrOW0fUpOEmoVq1XYuW8h5/U1VQkF9Q89FBXbIDy',
  NOW(),
  false,
  'local',
  'light',
  'America/Sao_Paulo',
  true,
  0,
  false,
  'pt-BR',
  '987.654.321-00',     -- CPF exemplo
  '1995-05-20',         -- Data de nascimento exemplo
  '29d2d8e3-6165-4e80-a480-6ab4f6d7acd1',
  NOW(),
  NOW()
);
